{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ratelimiter.serviceAccountName" . }}
  labels:
    {{- include "ratelimiter.labels" . | nindent 4 }}
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ template "ratelimiter.namespace" . }}
{{- end }}
